spring:
    application:
        name: clube-service
    jpa:
        generate-ddl: true
server:
    port: ${port}
    
eureka:
   client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka
        
        
    